version: 0.1
env:
    secrets-manager:
      TOKEN: SonarCloud_Secret:SonarCloud_Token
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojaws -Dsonar.organization=javaprojaws -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 
