version: 0.1
env:
    secrets-manager:
      TOKEN: SonarCloud_Secret:SonarCloud_Token
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojaws -Dsonar.organization=javaprojaws -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=javaprojectaws | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
